!= is instead of not_equal
---> 15     n_changes = np.not_equal(policy, new_policy).sum()

TypeError: ufunc 'not_equal' did not contain a loop with signature matching types dtype('<U2') dtype('<U2') dtype('bool')